function plotWebsiteFigures_v2(state_id,last_day,forecast_date)
% Updated 10/3/20
   
% Raw (un-smoothed) version of data
[C,G,~,HC,HG,DC,DG]  = loadStateCases_noscale_nosmooth(state_id);
% Smooth version of case count data
[currCsm,currGsm,~,~,~,currDCsm,currDGsm] = loadStateCases_noscale_v2(state_id,forecast_date);

% C = DC;
% G = DG;
% currCsm = currDCsm;
% currGsm = currDGsm; 

quantsC_0 = csvread(['quantile_forecasts/C_' state_id '_' forecast_date '.csv']);
quantsG_0 = csvread(['quantile_forecasts/G_' state_id '_' forecast_date '.csv']);

quantsG_0 = [currGsm(last_day)*ones(23,1), quantsG_0];

% quantsC_0 = [quantsC_0+currCsm(last_day-1);
quantsC_0 = [currCsm(last_day)*ones(23,1), currCsm(last_day)+quantsC_0];

ndp = length(quantsG_0(1,:))-1;

N = min(last_day+ndp,length(G));


median_forecast = quantsG_0(12,:);
medianC_forecast = quantsC_0(12,:);
maxCY = quantsC_0(end,end);
maxGY = 1.1*max(G);
[~, ~,date_array] = get_observation_index(state_id,...
                                forecast_date,5);

forecast_period = datetime({forecast_date});


for j = 1:ndp
    forecast_period = [forecast_period; datetime({forecast_date})+j];

end

figure(); hold on; box on;
    set(gca,'FontSize',16)
    plot(forecast_period,quantsG_0,'Color',0.7*[1,1,1],...
        'LineWidth',1.5,'HandleVisibility','off')
    plot(forecast_period,median_forecast,'Color',0*[1,1,1],...
        'LineWidth',3,'DisplayName','Forecast Median')    
%     plot(datetime(date_array(1:N)),G(1:N),'o-','LineWidth',1,...
%         'DisplayName','Reported Cases',...
%         'Color',[3, 175, 252]/255)
    plot(datetime(date_array(1:last_day)),G(1:last_day),'o-','LineWidth',1,...
        'DisplayName','Reported Cases',...
        'Color',[3, 175, 252]/255)
    plot(datetime(date_array(last_day+1:N)),G(last_day+1:N),'o','LineWidth',1,...
        'DisplayName','Reported Cases',...
        'Color',[3, 175, 252]/255,...
        'HandleVisibility','off')
%     plot(datetime(date_array(1:N)),currGsm(1:N),'LineWidth',3,...
%         'Color',[3, 127, 252]/255,...
%         'DisplayName','Time Averaged Cases')
    plot(datetime(date_array(1:last_day)),currGsm(1:last_day),'LineWidth',3,...
        'Color',[3, 127, 252]/255,...
        'DisplayName','Time Averaged Cases')
    plot(datetime(date_array(last_day+1:N)),currGsm(last_day+1:N),'-',...
        'LineWidth',3,...
        'Color',[3, 127, 252]/255,...
        'DisplayName','Time Averaged Cases',...
        'HandleVisibility','off')
    plot([datetime({forecast_date}), datetime({forecast_date})],[0,1.01*maxGY],'--r',...
        'DisplayName','Forecast Date',...
        'LineWidth',1.5)
    plot(forecast_period(1),quantsG_0(1,1),'Color',0.7*[1,1,1],...
        'LineWidth',1.5,'DisplayName','Forecast Quantiles')
    legend('Location','Northwest')
    datetick('x','mmm-dd')
    tstart = datetime(date_array(1));
    tend = forecast_period(end)+1; 
    xlim([tstart tend]);
    ylim([0,1.01*maxGY]);
    ylabel('Confirmed Cases')
    xlabel('Date')
    title([state_id newline ' Forecast Date: ' forecast_date])


    
    
    
figure(); hold on; box on;
    set(gca,'FontSize',16)
    plot(forecast_period,quantsC_0,'Color',0.7*[1,1,1],...
        'LineWidth',1.5,'HandleVisibility','off')
    plot(forecast_period,medianC_forecast,'Color',0*[1,1,1],...
        'LineWidth',3,'DisplayName','Forecast Median')
%     plot(datetime(date_array(1:N)),C(1:N),'o-','LineWidth',1,...
%         'DisplayName','Reported Cases',...
%         'Color',[3, 175, 252]/255)
%     plot(datetime(date_array(1:N)),currCsm(1:N),'LineWidth',3,...
%         'Color',[3, 127, 252]/255,...
%         'DisplayName','Time Averaged Cases')
    plot(datetime(date_array(1:last_day)),C(1:last_day),'o-','LineWidth',1,...
        'DisplayName','Reported Cases',...
        'Color',[3, 175, 252]/255)
    plot(datetime(date_array(last_day+1:N)),C(last_day+1:N),'o','LineWidth',1,...
        'DisplayName','Reported Cases',...
        'Color',[3, 175, 252]/255,...
        'HandleVisibility','off')
    plot(datetime(date_array(1:last_day)),currCsm(1:last_day),'LineWidth',3,...
        'Color',[3, 127, 252]/255,...
        'DisplayName','Time Averaged Cases')
    plot(datetime(date_array(last_day+1:N)),currCsm(last_day+1:N),'-',...
        'LineWidth',3,...
        'Color',[3, 127, 252]/255,...
        'DisplayName','Time Averaged Cases',...
        'HandleVisibility','off')
    plot([datetime({forecast_date}), datetime({forecast_date})],[0,1.01*maxCY],'--r',...
        'DisplayName','Forecast Date',...
        'LineWidth',1.5)
    plot(forecast_period(1),quantsC_0(1,1),'Color',0.7*[1,1,1],...
        'LineWidth',1.5,'DisplayName','Forecast Quantiles')
    legend('Location','Northwest')
    datetick('x','mmm-dd')
    tstart = datetime(date_array(1));
    tend = forecast_period(end)+1; 
    xlim([tstart tend]);
    ylim([0,1.01*maxCY]);
    ylabel('Cumulative Confirmed Cases')
    xlabel('Date')
    title([state_id newline ' Forecast Date: ' forecast_date])
   




